server:
  port: 8083

spring:
  application:
    name: follow-service
  datasource:
    url: jdbc:mariadb://localhost:3306/instagram_follows?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
