server:
  port: 8081 # Using 8081 to avoid conflict with frontend or other services

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mariadb://localhost:3306/instagram_auth?createDatabaseIfNotExist=true
    username: root
    password: password # User can adjust if needed
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Resilience4j Circuit Breaker Config
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 30
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 40s
        failureRateThreshold: 100 # Opens if all 5 calls fail
        permittedNumberOfCallsInHalfOpenState: 1
    instances:
      loginCircuitBreaker:
        baseConfig: default
