server:
  port: 8082

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:mariadb://localhost:3306/instagram_posts?createDatabaseIfNotExist=true
    username: root
    password: password # Same as auth service assumption
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
