server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mariadb://localhost:3306/instagram_notifications?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
